import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PageLayout from '../components/PageLayout';
import { EmptyStatePanel, LoadingSkeleton, SectionCard, StatusBadge } from '../components/DashboardPrimitives';
import { useToast } from '../contexts/ToastContext';
import { convertCrmLead, getCrmConvertibleLeads, getCrmDuplicates, importCrmRows } from '../lib/apiClient';

function csv(text: string) { const lines = text.replace(/\r/g,'').split('\n').filter(Boolean); if (lines.length < 2) return []; const headers = lines[0].split(',').map(x => x.trim().replace(/^"|"$/g,'')); return lines.slice(1).map(line => Object.fromEntries(line.split(',').map((value,index) => [headers[index], value.trim().replace(/^"|"$/g,'')]))); }

export default function CrmDataPage() {
  const navigate = useNavigate(); const toast = useToast(); const [leads,setLeads] = useState<any[]>([]); const [duplicates,setDuplicates] = useState<any[]>([]); const [loading,setLoading] = useState(true); const [kind,setKind] = useState<'companies'|'contacts'>('companies');
  const load = useCallback(async () => { setLoading(true); try { const [leadData,duplicateData] = await Promise.all([getCrmConvertibleLeads(),getCrmDuplicates()]); setLeads(leadData.items); setDuplicates(duplicateData.groups); } catch(e:any) { toast.push(e?.message || 'Unable to load CRM data tools','error'); } finally { setLoading(false); } },[]);
  useEffect(() => { void load(); },[load]);
  const upload = async (file: File) => { try { const rows = csv(await file.text()); if (!rows.length) throw new Error('No CSV rows found'); const result = await importCrmRows(kind,file.name,rows); toast.push(`Imported ${result.inserted}; skipped ${result.skipped}`,'success'); await load(); } catch(e:any) { toast.push(e?.message || 'Import failed','error'); } };
  return <PageLayout title="CRM data" eyebrow="Data management" description="Import records, convert inbound leads, and review possible duplicates." actions={<button className="vs-button-secondary" onClick={() => navigate('/crm')}>Back to CRM</button>}>{loading ? <LoadingSkeleton className="h-[500px]" /> : <div className="grid gap-5 xl:grid-cols-2"><div className="space-y-5"><SectionCard title="CSV import" description="Company columns: name, phone, city, state, industry, source, notes. Contact columns: first_name, last_name, phone, email, title."><div className="flex gap-3"><select value={kind} onChange={e => setKind(e.target.value as any)} className="vs-input h-10"><option value="companies">Companies</option><option value="contacts">Contacts</option></select><label className="vs-button-primary cursor-pointer">Choose CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={e => { const file=e.target.files?.[0]; if(file) void upload(file); }} /></label></div></SectionCard><SectionCard title="Possible duplicates" description="Matches are detected by normalized phone, email, or company name.">{duplicates.length ? <div className="space-y-3">{duplicates.map((group,index) => <div key={`${group.match}-${index}`} className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex justify-between"><strong className="capitalize text-slate-900">{group.kind} match</strong><StatusBadge tone="warning">{group.records.length} records</StatusBadge></div><div className="mt-1 text-xs text-slate-500">{group.match}</div><div className="mt-3 text-sm text-slate-700">{group.records.map((r:any) => r.name || `${r.first_name || ''} ${r.last_name || ''}`).join(' · ')}</div></div>)}</div> : <EmptyStatePanel title="No duplicate groups" description="No matching CRM records were found." />}</SectionCard></div><SectionCard title="Convert leads" description="Create a linked CRM company, contact, and optional opportunity from existing lead intake.">{leads.length ? <div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{leads.map(lead => <div key={lead.id} className="py-4"><div className="font-bold text-slate-950">{lead.first_name} {lead.last_name}</div><div className="text-xs text-slate-500">{lead.email || lead.phone} · {lead.source || 'Unknown source'}</div><form className="mt-3 flex gap-2" onSubmit={async e => { e.preventDefault(); const name=String(new FormData(e.currentTarget).get('company_name') || ''); try { await convertCrmLead(lead.id,name,true); toast.push('Lead converted to CRM','success'); await load(); } catch(error:any) { toast.push(error?.message || 'Conversion failed','error'); } }}><input name="company_name" required className="vs-input h-10 flex-1" placeholder="Company name" /><button className="vs-button-primary">Convert</button></form></div>)}</div> : <EmptyStatePanel title="No unconverted leads" description="All recent leads have already been converted." />}</SectionCard></div>}</PageLayout>;
}
