import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PageLayout from '../components/PageLayout';
import { LoadingSkeleton, SectionCard, StatusBadge } from '../components/DashboardPrimitives';
import { useToast } from '../contexts/ToastContext';
import { createCrmStage, CrmOutcomeMapping, getCrmSettings, PipelineStage, reorderCrmStages, updateCrmOutcomeMapping, updateCrmStage } from '../lib/apiClient';

const outcomes = ['connected', 'no_answer', 'voicemail', 'callback', 'qualified', 'trial_booked', 'not_interested'];

export default function CrmSettingsPage() {
  const navigate = useNavigate(); const toast = useToast();
  const [orgId, setOrgId] = useState(''); const [stages, setStages] = useState<PipelineStage[]>([]); const [mappings, setMappings] = useState<CrmOutcomeMapping[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const data = await getCrmSettings(); setOrgId(data.organization_id); setStages(data.stages); setMappings(data.mappings); } catch (e: any) { toast.push(e?.message || 'Unable to load CRM settings', 'error'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const addStage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await createCrmStage({ organization_id: orgId, name: data.get('name'), position: stages.length ? Math.max(...stages.map(s => s.position)) + 10 : 10, color: data.get('color'), is_closed: false, is_won: false }); event.currentTarget.reset(); toast.push('Pipeline stage added', 'success'); await load(); } catch (e: any) { toast.push(e?.message || 'Unable to add stage', 'error'); } };
  const move = async (index: number, delta: number) => { const next = [...stages]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setStages(next); try { await reorderCrmStages(orgId, next.map(s => s.id)); toast.push('Stage order saved', 'success'); await load(); } catch (e: any) { toast.push(e?.message || 'Unable to reorder stages', 'error'); await load(); } };
  if (loading) return <PageLayout title="CRM settings"><LoadingSkeleton className="h-[480px]" /></PageLayout>;
  return <PageLayout title="CRM settings" eyebrow="Internal CRM" description="Configure the pipeline and automatic call-outcome movement." actions={<button className="vs-button-secondary" onClick={() => navigate('/crm')}>Back to CRM</button>}><div className="grid gap-5 xl:grid-cols-2">
    <SectionCard title="Pipeline stages" description="Rename stages and control their display order."><div className="space-y-2">{stages.map((stage,index) => <div key={stage.id} className="grid grid-cols-[auto_1fr_auto_auto] items-center gap-2 rounded-2xl border border-slate-200 p-3"><div className="flex flex-col"><button className="text-xs" disabled={index===0} onClick={() => void move(index,-1)}>▲</button><button className="text-xs" disabled={index===stages.length-1} onClick={() => void move(index,1)}>▼</button></div><input className="vs-input h-10" defaultValue={stage.name} onBlur={async e => { if (e.target.value.trim() !== stage.name) { await updateCrmStage(stage.id,{name:e.target.value.trim()}); toast.push('Stage renamed','success'); await load(); } }} /><label className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={stage.is_closed} onChange={async e => { await updateCrmStage(stage.id,{is_closed:e.target.checked,is_won:e.target.checked ? stage.is_won : false}); await load(); }} />Closed</label>{stage.is_won ? <StatusBadge tone="success">Won</StatusBadge> : <button className="vs-button-ghost text-xs" onClick={async () => { await updateCrmStage(stage.id,{is_won:true,is_closed:true}); await load(); }}>Mark won</button>}</div>)}</div><form onSubmit={addStage} className="mt-4 grid grid-cols-[1fr_130px_auto] gap-2"><input name="name" required className="vs-input h-10" placeholder="New stage name" /><select name="color" className="vs-input h-10"><option value="slate">Slate</option><option value="violet">Violet</option><option value="sky">Sky</option><option value="amber">Amber</option><option value="emerald">Emerald</option><option value="rose">Rose</option></select><button className="vs-button-primary">Add</button></form></SectionCard>
    <SectionCard title="Call outcome automation" description="Choose where an opportunity moves after each logged call outcome."><div className="space-y-3">{outcomes.map(outcome => { const mapping = mappings.find(m => m.outcome === outcome); return <div key={outcome} className="grid grid-cols-[1fr_1.2fr_auto] items-center gap-3 rounded-2xl border border-slate-200 p-3"><div className="text-sm font-bold capitalize text-slate-900">{outcome.replace('_',' ')}</div><select value={mapping?.target_stage_id || ''} className="vs-input h-10" onChange={async e => { if (!e.target.value) return; await updateCrmOutcomeMapping(outcome,{organization_id:orgId,target_stage_id:e.target.value,enabled:true}); toast.push('Automation saved','success'); await load(); }}><option value="">No automatic move</option>{stages.map(stage => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><input type="checkbox" checked={mapping?.enabled || false} disabled={!mapping} onChange={async e => { if (!mapping) return; await updateCrmOutcomeMapping(outcome,{organization_id:orgId,target_stage_id:mapping.target_stage_id,enabled:e.target.checked}); await load(); }} /></div>; })}</div></SectionCard>
  </div></PageLayout>;
}
