import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PageLayout from '../components/PageLayout';
import { EmptyStatePanel, FilterBar, LoadingSkeleton, SearchInput, SectionCard, SegmentedControl, StatusBadge } from '../components/DashboardPrimitives';
import { useToast } from '../contexts/ToastContext';
import { CrmTask, getCrmTasks, updateCrmTask } from '../lib/apiClient';

type Scope = 'today' | 'overdue' | 'upcoming' | 'completed';
type TaskRow = CrmTask & { contact?: { id: string; first_name: string; last_name?: string }; deal?: { id: string; title: string } };

export default function CrmTasksPage() {
  const navigate = useNavigate(); const toast = useToast();
  const [scope, setScope] = useState<Scope>('today'); const [tasks, setTasks] = useState<TaskRow[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const data = await getCrmTasks({ completed: scope === 'completed' }); setTasks(data.items); } catch (e: any) { toast.push(e?.message || 'Unable to load tasks', 'error'); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { void load(); }, [load]);
  const now = new Date(); const start = new Date(now); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(end.getDate()+1);
  const visible = useMemo(() => tasks.filter(task => { const due = new Date(task.due_date); const text = `${task.title} ${task.company?.name || ''} ${task.contact?.first_name || ''} ${task.deal?.title || ''}`.toLowerCase(); if (search && !text.includes(search.toLowerCase())) return false; if (scope === 'completed') return task.completed; if (scope === 'overdue') return due < start; if (scope === 'today') return due >= start && due < end; return due >= end; }), [tasks,scope,search]);
  const complete = async (task: TaskRow, value: boolean) => { try { await updateCrmTask(task.id,value); toast.push(value ? 'Task completed' : 'Task reopened','success'); await load(); } catch (e:any) { toast.push(e?.message || 'Unable to update task','error'); } };
  return <PageLayout title="Tasks" eyebrow="CRM workspace" description="A single follow-up queue across companies, contacts, and opportunities." actions={<><button className="vs-button-secondary" onClick={() => navigate('/crm')}>Back to CRM</button><button className="vs-button-primary" onClick={() => navigate('/crm')}>Create from record</button></>}><div className="space-y-4"><FilterBar><SegmentedControl value={scope} onChange={setScope} options={[{value:'today',label:'Today'},{value:'overdue',label:'Overdue'},{value:'upcoming',label:'Upcoming'},{value:'completed',label:'Completed'}]} /><SearchInput value={search} onChange={setSearch} placeholder="Search tasks, companies, or deals..." /></FilterBar>{loading ? <LoadingSkeleton className="h-96" /> : <SectionCard title={`${scope[0].toUpperCase()}${scope.slice(1)} tasks`} description={`${visible.length} task${visible.length === 1 ? '' : 's'} in this view`}>{visible.length ? <div className="divide-y divide-slate-100">{visible.map(task => <div key={task.id} className="grid gap-3 py-4 sm:grid-cols-[auto_1fr_auto] sm:items-center"><input type="checkbox" checked={task.completed} onChange={e => void complete(task,e.target.checked)} /><button className="text-left" onClick={() => navigate(`/crm/companies/${task.company_id}`)}><div className={`font-bold ${task.completed ? 'text-slate-400 line-through' : 'text-slate-950'}`}>{task.title}</div><div className="mt-1 text-xs text-slate-500">{task.company?.name || 'Company'}{task.deal?.title ? ` · ${task.deal.title}` : ''}{task.contact ? ` · ${task.contact.first_name} ${task.contact.last_name || ''}` : ''}</div></button><div className="text-right"><StatusBadge tone={!task.completed && new Date(task.due_date) < now ? 'danger' : task.completed ? 'success' : 'warning'}>{task.completed ? 'Done' : new Date(task.due_date) < now ? 'Overdue' : 'Open'}</StatusBadge><div className="mt-1 text-xs text-slate-500">{new Date(task.due_date).toLocaleString()}</div></div></div>)}</div> : <EmptyStatePanel title="No tasks in this view" description="Tasks created from CRM records will appear here." />}</SectionCard>}</div></PageLayout>;
}
