import express from 'express';
import { z } from 'zod';
import { isPlatformAdmin } from '../auth/rbac';
import { supabaseAdmin } from '../lib/supabaseClient';

const router = express.Router(); const uuid=z.string().uuid();
function actor(req: express.Request){const id=String((req as any).actorId||'');if(!id)throw Object.assign(new Error('unauthenticated'),{status:401});return id;}
async function context(req: express.Request){const userId=actor(req);if(!(await isPlatformAdmin(userId)))throw Object.assign(new Error('forbidden'),{status:403});const configured=String(process.env.VICTORYSYNC_DEFAULT_ORG_ID||'').trim();if(configured)return {userId,orgId:uuid.parse(configured)};const {data}=await supabaseAdmin.from('organizations').select('id,name').limit(100);const org=(data||[]).find((x:any)=>/victory\s*sync/i.test(String(x.name||'')));if(!org)throw Object.assign(new Error('internal_crm_organization_not_configured'),{status:409});return {userId,orgId:String(org.id)};}
function fail(res:express.Response,e:any,name:string){res.status(Number(e?.status||(e instanceof z.ZodError?400:500))).json({error:e instanceof z.ZodError?'invalid_request':e?.message||name,issues:e instanceof z.ZodError?e.issues:undefined});}

router.get('/sales/workspace',async(req,res)=>{try{const {orgId}=await context(req);const [products,quotes,sequences,meetings,goals,deals,stages]=await Promise.all([
supabaseAdmin.from('crm_products').select('*').eq('organization_id',orgId).order('name'),supabaseAdmin.from('crm_quotes').select('*,deal:crm_deals(id,title)').eq('organization_id',orgId).order('created_at',{ascending:false}),supabaseAdmin.from('sales_sequences').select('*,steps:sales_sequence_steps(*)').eq('organization_id',orgId).order('name'),supabaseAdmin.from('crm_meetings').select('*,company:crm_companies(id,name),contact:crm_contacts(id,first_name,last_name)').eq('organization_id',orgId).order('starts_at'),supabaseAdmin.from('sales_goals').select('*').eq('organization_id',orgId).order('period_end'),supabaseAdmin.from('crm_deals').select('id,title,amount,probability,close_date,stage_id,company:crm_companies(id,name)').eq('organization_id',orgId),supabaseAdmin.from('crm_pipeline_stages').select('*').eq('organization_id',orgId).order('position')]);
for(const x of [products,quotes,sequences,meetings,goals,deals,stages])if(x.error)throw x.error;const pipeline=(deals.data||[]).reduce((sum:any,d:any)=>{sum.total+=Number(d.amount||0);sum.weighted+=Number(d.amount||0)*Number(d.probability||0)/100;return sum;},{total:0,weighted:0});res.json({organization_id:orgId,products:products.data||[],quotes:quotes.data||[],sequences:sequences.data||[],meetings:meetings.data||[],goals:goals.data||[],deals:deals.data||[],stages:stages.data||[],forecast:pipeline});}catch(e){fail(res,e,'sales_workspace_failed')}});
router.post('/sales/products',async(req,res)=>{try{const {userId,orgId}=await context(req);const input=z.object({name:z.string().trim().min(1),sku:z.string().trim().nullable().optional(),description:z.string().nullable().optional(),unit_price:z.number().min(0),currency:z.string().length(3).default('USD')}).parse(req.body);const {data,error}=await supabaseAdmin.from('crm_products').insert({...input,organization_id:orgId,created_by:userId}).select('*').single();if(error)throw error;res.status(201).json({item:data});}catch(e){fail(res,e,'product_create_failed')}});
router.post('/sales/quotes',async(req,res)=>{try{const {userId,orgId}=await context(req);const input=z.object({deal_id:uuid,title:z.string().min(1),subtotal:z.number().min(0),discount:z.number().min(0).default(0),tax:z.number().min(0).default(0),expires_at:z.string().datetime().nullable().optional(),terms:z.string().nullable().optional()}).parse(req.body);const total=input.subtotal-input.discount+input.tax;const quote_number=`VS-${Date.now().toString(36).toUpperCase()}`;const {data,error}=await supabaseAdmin.from('crm_quotes').insert({...input,total,quote_number,organization_id:orgId,created_by:userId}).select('*').single();if(error)throw error;res.status(201).json({item:data});}catch(e){fail(res,e,'quote_create_failed')}});
router.post('/sales/meetings',async(req,res)=>{try{const {userId,orgId}=await context(req);const input=z.object({company_id:uuid.nullable().optional(),contact_id:uuid.nullable().optional(),deal_id:uuid.nullable().optional(),title:z.string().min(1),starts_at:z.string().datetime(),ends_at:z.string().datetime(),location:z.string().nullable().optional(),notes:z.string().nullable().optional()}).parse(req.body);const {data,error}=await supabaseAdmin.from('crm_meetings').insert({...input,organization_id:orgId,assigned_to:userId,created_by:userId}).select('*').single();if(error)throw error;res.status(201).json({item:data});}catch(e){fail(res,e,'meeting_create_failed')}});
router.post('/sales/goals',async(req,res)=>{try{const {userId,orgId}=await context(req);const input=z.object({name:z.string().min(1),metric:z.enum(['revenue','deals_won','calls','meetings']),target_value:z.number().positive(),period_start:z.string(),period_end:z.string()}).parse(req.body);const {data,error}=await supabaseAdmin.from('sales_goals').insert({...input,organization_id:orgId,owner_id:userId}).select('*').single();if(error)throw error;res.status(201).json({item:data});}catch(e){fail(res,e,'goal_create_failed')}});
router.post('/sales/sequences',async(req,res)=>{try{const {userId,orgId}=await context(req);const input=z.object({name:z.string().min(1),description:z.string().nullable().optional(),steps:z.array(z.object({type:z.enum(['email','call','task']),delay_days:z.number().int().min(0),subject:z.string().nullable().optional(),body:z.string().nullable().optional(),task_title:z.string().nullable().optional()})).min(1)}).parse(req.body);const created=await supabaseAdmin.from('sales_sequences').insert({organization_id:orgId,name:input.name,description:input.description,created_by:userId}).select('*').single();if(created.error)throw created.error;const rows=input.steps.map((step,index)=>({...step,organization_id:orgId,sequence_id:created.data.id,position:index+1}));const stepResult=await supabaseAdmin.from('sales_sequence_steps').insert(rows);if(stepResult.error)throw stepResult.error;res.status(201).json({item:created.data});}catch(e){fail(res,e,'sequence_create_failed')}});
export default router;
